# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors_control', models.IntegerField()),
                ('visitors_variant', models.IntegerField()),
                ('conversion_control', models.IntegerField()),
                ('conversion_variant', models.IntegerField()),
                ('p_value', models.FloatField()),
                ('significance', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
                'db_table': ('result',),
            },
        ),
    ]
